version: "2"

run:
  deadline: 5m
  tests: false

linters:
  default: none
  enable:
  - errcheck
  - copyloopvar
  - gochecknoinits
  - gocritic
  - gomodguard
  - gosec
  - govet
  - ineffassign
  - misspell
  - revive
  - staticcheck
  - unconvert
  - unparam
  - unused
  - whitespace