---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: macvlan-enp0s10-attachment-b
  labels:
    app: demo-b
spec:
  spec:
    devices:
      requests:
      - name: macvlan-enp0s10
        deviceClassName: cni.networking.x-k8s.io
        allocationMode: ExactCount
        count: 1
        capacities:
          requests:
            bandwidth: 5Gi
        selectors:
        - cel:
            expression: device.driver == "cni.dra.networking.x-k8s.io"
        - cel:
            expression: device.attributes["cni.dra.networking.x-k8s.io"].name == "enp0s10"
      config:
      - requests:
        - macvlan-enp0s10
        opaque:
          driver: cni.dra.networking.x-k8s.io
          parameters: # CNIParameters with the GVK, interface name and CNI Config (in YAML format).
            apiVersion: cni.networking.x-k8s.io/v1alpha1
            kind: CNI
            ifName: "net1"
            config:
              cniVersion: 1.0.0
              name: macvlan-enp0s10
              plugins:
              - type: macvlan
                master: enp0s10
                mode: bridge
                ipam:
                  type: host-local
                  ranges:
                  - - subnet: 10.10.1.0/24
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-b
  labels:
    app: demo-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-b
  template:
    metadata:
      labels:
        app: demo-b
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - infinity
      resourceClaims:
      - name: macvlan-enp0s10-attachment-b
        resourceClaimTemplateName: macvlan-enp0s10-attachment-b