---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "DynamicResourceAllocation": true
  "DRAResourceClaimDeviceStatus": true
  "DRAAdminAccess": true
  "DRAConsumableCapacity": true
runtimeConfig:
  "resource.k8s.io/v1beta1": true
  "resource.k8s.io/v1beta2": true
nodes:
- role: control-plane
  image: ghcr.io/sunya-ch/kindest/node:kep-5075-2a38e52ce37152215fe074eed5762fb01c36e347
- role: worker
  image: ghcr.io/sunya-ch/kindest/node:kep-5075-2a38e52ce37152215fe074eed5762fb01c36e347
- role: worker
  image: ghcr.io/sunya-ch/kindest/node:kep-5075-2a38e52ce37152215fe074eed5762fb01c36e347