---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: macvlan-eth0-attachment
spec:
  spec:
    devices:
      requests:
      - name: macvlan-eth0
        deviceClassName: cni.networking.x-k8s.io
        allocationMode: ExactCount
        count: 1
      config:
      - requests:
        - macvlan-eth0
        opaque:
          driver: cni.dra.networking.x-k8s.io
          parameters: # CNIParameters with the GVK, interface name and CNI Config (in YAML format).
            apiVersion: cni.networking.x-k8s.io/v1alpha1
            kind: CNI
            ifName: "net1"
            config:
              cniVersion: 1.0.0
              name: macvlan-eth0
              plugins:
              - type: macvlan
                master: eth0
                mode: bridge
                ipam:
                  type: host-local
                  ranges:
                  - - subnet: 10.10.1.0/24
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-b
  labels:
    app: demo-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-b
  template:
    metadata:
      labels:
        app: demo-b
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        - infinity
      resourceClaims:
      - name: macvlan-eth0-attachment
        resourceClaimTemplateName: macvlan-eth0-attachment